language: bash

services:
  - docker

before_install:
  - docker build -t oskarv/snakemake-germline-tools .

script:
  - docker run -ti oskarv/snakemake-germline-tools gatk --version
  - docker run -ti oskarv/snakemake-germline-tools samtools