# TSV file format:
#flowcell  sample  library lane  R1  R2
# N.B, don't just copy/paste the header above, separate the columns with a tab space.

# The samples.tsv file contains all sample information.
# all columns, except for R1 and R2, are used to construct the read group.
samples: /data/samples.tsv

# This is a variable that is used to define how many sub interval lists should be created \
# from the full interval list. Tune this according to taste or based on the available \
# compute resources. 
scattercount: 30

# file paths to the various reference files
b37:
  contigfiles: 18 # This is a hack, don't change this unless you know what you are doing. This number is determined dynamically and depends on the reference.dict contigs. If you change or add a reference version you must run the split-bedfile.py and MakeTSVs.sh scripts to see how many bed files are created and then set this variable to that number, this should be fixed to avoid this hacky solution.
  fasta: "/references/b37/human_g1k_v37_decoy.fasta"
  fai: "/references/b37/human_g1k_v37_decoy.fasta.fai"
  dict: "/references/b37/human_g1k_v37_decoy.dict"
  dbsnp: "/references/b37/dbsnp.vcf"
  hapmap: "/references/b37/hapmap.vcf"
  omni: "/references/b37/omni.vcf"
  v1000g: "/references/b37/1000G_phase1.indels.b37.vcf"
  mills: "/references/b37/1000g.vcf"
  intervals: "/references/b37/b37_wgs_calling_regions.v1.interval_list"

hg38:
  contigfiles: 19 # This is a hack, don't change this unless you know what you are doing. This number is determined dynamically and depends on the reference.dict contigs. If you change or add a reference version you must run the split-bedfile.py and MakeTSVs.sh scripts to see how many bed files are created and then set this variable to that number, this should be fixed to avoid this hacky solution.
  fasta: "/references/hg38/Homo_sapiens_assembly38.fasta"
  fai: "/references/hg38/Homo_sapiens_assembly38.fasta.fai"
  dict: "/references/hg38/Homo_sapiens_assembly38.dict"
  dbsnp: "/references/hg38/dbsnp_146.hg38.vcf.gz"
  hapmap: "/references/hg38/hapmap_3.3.hg38.vcf.gz"
  omni: "/references/hg38/1000G_omni2.5.hg38.vcf.gz"
  v1000g: "/references/hg38/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
  mills: "/references/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  intervals: "/references/hg38/wgs_calling_regions.hg38.interval_list"